### ISSUE TITLE
demo site is failing

### ISSUE THREAD

**Issue by jochengcd** [django-helpdesk/django-helpdesk#1004]
**Describe the bug**
When trying the enter a ticker or login, one gets:

Forbidden (403)

CSRF verification failed. Request aborted.

You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties.

**To Reproduce**
any try to enter a ticket/login.

**Expected behavior**
login/ticket working

**Desktop (please complete the following information):**
 - OS: linux
 - Browser: firefox, chrome

**Comment by gwasser** [comment]
thanks, interesting, it used to work not long ago. I'm trying to remember if it used to use TLS, it seems as if Heroku isn't using TLS encryption so maybe that's messing with the CSRF protection?

i'm not sure that any of our recent patches would have impacted this but maybe.

**Comment by gwasser** [comment]
We figured this out. You need to use the https link. Previously the docs directed folks to http and so the CSRF wouldn't work because there was no https.

So use this correct link for the demo: https://django-helpdesk-demo.herokuapp.com/

We updated the docs to give this link so should be good everywhere, but let us know if we missed a link somewhere.

Thanks!
