### ISSUE TITLE
Update demo to Django 4

### ISSUE THREAD

**Issue by mr-vaibh** [django-helpdesk/django-helpdesk#1049]
I think it is high time now that we must update the demo to Django 4.

There are so many breaking changes in this package with respect to Django 4, as there are some functions deprecated in the latest version of Django.

I'll keep updating this issue as I discover more breaking changes. For now, I request someone to start setting up a fresh demo site.

PS: The current demo site is using Django 1.1, which is really non-reliable as of today.

**Comment by gwasser** [comment]
Do you mean the demo site at: https://django-helpdesk-demo.herokuapp.com/?

It is currently running the latest stable release (0.4.1) on Django 3.2.

I do agree the demo script in the repo is broken and needs to be updated. I'm sure we'll update it once our next release settles out because it has a lot of good changes in it already. I am not sure when that is coming though, will have to talk with the volunteers that are working on updating us to Django 4 and fixing up the code base.

**Comment by mr-vaibh** [comment]
Yess, I mean the demo folder, this - https://github.com/django-helpdesk/django-helpdesk/tree/stable/demo
It's [`settings.py` ](https://github.com/django-helpdesk/django-helpdesk/blob/stable/demo/demodesk/config/settings.py)shows Django 1.1

But anyways, ...the first error which I faced while a fresh start in Django 4 was this [ImportError : cannot import name 'ugettext_lazy'](https://stackoverflow.com/questions/70656495/importerror-cannot-import-name-ugettext-lazy), which is very easy to solve. I'll be posting a PR fix for that soon.

I'm ready to contribute all the way, I request all the support in the process.
And please try to create a new demo folder (presumably in a new branch) for the latest Django 4, as it is here to stay.

**Comment by gwasser** [comment]
Oh I see. Yes that's old file, the comments refer to Django 1.1 docs but it does work for newer versions of Django. The latest version of Django gets installed with the demo script, or at least it did but the script currently has some problems.

Contributions are appreciated! Please check the `unstable` branch and submit a PR against `unstable`, I think that's where we're doing all the Django 4 development at this point toward the next release. Thanks!

**Comment by uhurusurfa** [comment]
Django 4 now supported.
