### ISSUE TITLE
quicktests

### ISSUE THREAD

**Issue by brucegibbins** [django-helpdesk/django-helpdesk#1077]
Hello.

Running on Windows 11 and Python 3.9.5

when running quicktests.py I am getting the following error and them I get a number of 
helpdesk.models.Ticket.DoesNotExist: Ticket matching query does not exist.

> ======================================================================
> ERROR: test_email_with_8bit_encoding_and_utf_8 (helpdesk.tests.test_get_email.GetEmailCommonTests)
> Tests that emails with 8bit transfer encoding and utf-8 charset
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "C:\tgm\projects\python\django-helpdesk\helpdesk\tests\test_get_email.py", line 99, in test_email_with_8bit_encoding_and_utf_8
>     test_email = fd.read()
>   File "C:\tgm\bin\Python39\lib\encodings\cp1252.py", line 23, in decode
>     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 474: character maps to <undefined>
> 

I don't believe I have coded anything to influence the unicodedecodeerror but would also like to know of the proceeding tests are dependent on the ticket being created from this test?

thanks

**Comment by uhurusurfa** [comment]
The most likely cause of this is that there is no explicit character encoding defined for the "open" command so python will use the system default and it looks like your Windows setup is defaulting to the lgact CP-1252 character set instead of the modern UTF-8.
A fix for you is to change your system default character set to UTF-8.
The correct fix is to explicitly set the characterset in the open command on line 98 of test_get_email.py
`with open(os.path.join(THIS_DIR, "test_files/all-special-chars.eml", encoding="utf-8")) as fd:`

**Comment by brucegibbins** [comment]
Thanks. I'll try the patch to the line and see what happens.

Will also look into the default character set out of curiosity.

Appreciate the reply

**Comment by brucegibbins** [comment]
Patchin line 98 worked. Thanks
