### ISSUE TITLE
Why is the API optional?

### ISSUE THREAD

**Issue by timthelion** [django-helpdesk/django-helpdesk#1137]
@Benbb96 I see that you made the API optional: https://github.com/django-helpdesk/django-helpdesk/commit/dc60d8a7f95ed789872817bf3a7e269f38b5fc3e . I'm currently re-implementing the user tickets view for a client and I'd like to use rest. We can't use the REST API in the frontend if it gets turned off by some users. Why did you make this optional? Is it OK if I use the REST api in the frontend (in which case turning the API off will break the front end...)

**Comment by Benbb96** [comment]
Hi @timthelion

If I remember correctly, I added the setting `HELPDESK_ACTIVATE_API_ENDPOINT` in order to keep django-helpdesk the same for users already using it. Maybe they don't want an API to be exposed by default, so I made it an optional feature.

But indeed, if you build a frontend that require the API to be enabled, and someone who has access to settings change the parameter to False, yes it's not going to work well :smile: 

I'm not sure to understand your use case in fact. Are you developing a frontend for django-helpdesk (I mean you want this to be included in the package) or is it something external? If you are the one who maintain the backend, and you know the settings won't be changed, I see no problem to build a frontend based on that.

**Comment by timthelion** [comment]
I want to.implement the 'my tickets' view for logged in non staff users. I would submit a PR here when I'm done...

**Comment by Benbb96** [comment]
Alright, so I see two paths :

1. Used the setting to render either the current version which doesn't use the API when it's disabled, or render your new version when it's enabled.
2. Make the API always active (if we're sure it doesn't have any impact or security issues which I don't think it's the case)

**Comment by uhurusurfa** [comment]
The entire Helpdesk app needs to be migratged to a formal API and starting with the "My Tickets" view @timthelion  wants to implement means enabling it permanently makes sense.
