### ISSUE TITLE
RelatedObjectDoesNotExist errors

### ISSUE THREAD

**Issue by schmitthub** [django-helpdesk/django-helpdesk#283]
I get the RelatedObjectDoesNotExist at  ... error with the exception value being "User has no usersettings." when trying to view tickets, submit tickets, or change my settings. I just cloned the code about 10 minutes ago so it is the most recent release. Is there something wrong with my database configuration? I'm using postgresql.

**Comment by i25** [comment]
how to create a user

**Comment by reduxionist** [comment]
@i25 You should create a new issue rather than re-opening an old, closed, one unless you're having the same issue as the original poster (which you're not). 

That said, you can create new users through the Django admin or through a sign-up process you build or install another app for if you want self-signup. (django-helpdesk is a "pluggable" Django app, not a standalone helpdesk, and requires you to have an existing Django project to insert it into.) I recommend you try the django-users mailing list (http://groups.google.com/group/django-users/) or check the FAQ (https://docs.djangoproject.com/en/1.8/faq/admin/) if you have questions about the Django admin.

If you do have a *django-helpdesk specific* issue please create a new ticket for it. 

Closes #283
