### ISSUE TITLE
Enable reviews for pull requests

### ISSUE THREAD

**Issue by flinz** [django-helpdesk/django-helpdesk#427]
In course of the maintainer change and transition to an organization (#424) could we maybe enable [reviews for pull requests](https://help.github.com/articles/enabling-required-reviews-for-pull-requests/)? I think this is great feature to streamline the code review process a little, given that we're now 1+2 people who can merge.

I can't seem to enable it on the repository.

**Comment by gwasser** [comment]
I agree that code review would be great! But I also don't have access to the repo settings.

**Comment by rossp** [comment]
I've just made sure that organization members also have write access to the repository - I didn't realise that didn't flow down automatically, sorry... are you able to change that setting now?

**Comment by reduxionist** [comment]
I have set this up now, thanks @flinz and @rossp!

I did not include administrators under the requirement so that emergency commits can still be made as quickly as possible if necessary, but, personally, I will always await such a review before merging my own PRs otherwise (i.e. under normal circumstances).
