### ISSUE TITLE
ticket_from_message(message, queue, logger)

### ISSUE THREAD

**Issue by rando305** [django-helpdesk/django-helpdesk#456]
ticket_from_message now requires three arguments, but the calling instances in get_email.py only pass two.  (They aren't passing the logger).

**Comment by reduxionist** [comment]
Sorry you ran into this, thanks for reporting it. A patch is going through CI now and should be merged shortly.

**Comment by rando305** [comment]
In line 217 of get_email.py, msgNum is referenced prior to assignment.  I expect it is supposed to be just 'num'?

Two lines below is a similar problem.

I obviously don't know the correct way to alert this in github - I'd be appreciative of guidance on how to best provide feedback.

**Comment by reduxionist** [comment]
In this case, this way of alerting is fine; technically, each different bug should be filed under a new issue, but since these are all tiny ones in the same module (probably relating to the same commit too), I don't mind collecting them here.

In any case, I believe that this one is fixed in [a dev branch on my fork](https://github.com/reduxionist/django-helpdesk/tree/issue/multiple/attachments), and since the first one you reported above was also already fixed there,  I was hoping that perhaps you'd be willing to give that branch a try directly? If not I can keep pulling out patches and hot-fixing, I just prefer to keep the main tree clean when I have the option to merge a rebased version of a feature-branch later... Thanks for the reports in either case! 😄

**Comment by reduxionist** [comment]
Uhhh, unless you're on Django 1.8 and Python 3. Looks like I missed a string encoding update, but Travis just caught it for us so don't try my branch if those versions are your poison... 😉

**Comment by rando305** [comment]
No, I'm on 1.9 and Python 3.  

I've never pip ed from a branch before.

Is it just pip install git+https://github.com/reduxionist/django-helpdesk/  ?

**Comment by reduxionist** [comment]
Just to let you know, both of these patches have been merged into master now so you should be safe to install from the official source next time it comes up. Thanks again for the bug reports!

**Comment by reduxionist** [comment]
The results from Travis have just shown me I've broken my local test environment (pyenv + tox not going so well for me today), and it looks like issue is actually worse now because I got the difference in using the std. lib.'s email.message methods backwards and am actually throwing exceptions under Py3 despite what I believed my local testrunner was showing me. I'm going to have to fix my dev env before I can make any sensible approach, so now that at least you know where my code went bad please feel free to apply a fix if you're so inclined. Otherwise, I'll let you know once I'm back on it myself... 🙈

**Comment by reduxionist** [comment]
Whoops, wrong issue!
