### ISSUE TITLE
Parse html emails and render text content? 

### ISSUE THREAD

**Issue by willstott101** [django-helpdesk/django-helpdesk#504]
It can be a little frustrating if a user has an html email footer and a client which doesn't send a plain text version of the message. All messages are hidden and the conversation flow in the web interface is feels disjointed. It would be brilliant if the text content within the html could be grabbed and displayed. Even if it's not super pretty.

I understand the potential complications of parsing html (especially malformed) but I think it could add a lot of value.

The alternative approach being embedding documents in the conversation feed itself... feels a bit weird. Although it does hand the work and complications off to the browser which may be worth it.

Thanks for all your work on this app!

**Comment by gwasser** [comment]
I believe this issue was discussed in #304 without a super satisfactory resolution, but it's something we're thinking about!

I'm going to close this issue just to keep our issue tracker tidy, if you don't mind! But definitely let's continue conversation on #304 and see what we can do to resolve this.
