### ISSUE TITLE
Optimisation in num_to_link (eliminate ReverseProxy class)

### ISSUE THREAD

**Issue by mrkiwi-nz** [django-helpdesk/django-helpdesk#512]
What is the purpose of ReverseProxy in ticket_to_link.py?

```
def num_to_link(text):
    if text == '':
        return text

    matches = []
    for match in re.finditer(r"(?:[^&]|\b|^)#(\d+)\b", text):
        matches.append(match)

    for match in ReverseProxy(matches):
        start = match.start()
        end = match.end()
        number = match.groups()[0]
        url = reverse('helpdesk_view', args=[number])
        try:
            ticket = Ticket.objects.get(id=number)
        except Ticket.DoesNotExist:
            ticket = None

        if ticket:
            style = ticket.get_status_display()
            text = "%s <a href='%s' class='ticket_link_status ticket_link_status_%s'>#%s</a>%s" % (text[:match.start()], url, style, match.groups()[0], text[match.end():])
    return mark_safe(text)

register = template.Library()
register.filter(num_to_link)
```

What does ReverseProxy() do (see below) that reversed() would not do?
Why use a custom class over the builtin reversed?

```
class ReverseProxy:
    def __init__(self, sequence):
        self.sequence = sequence

    def __iter__(self):
        length = len(self.sequence)
        i = length
        while i > 0:
            i = i - 1
            yield self.sequence[i]
```

**Comment by gwasser** [comment]
Very good questions! It looks to me like it's going backwards through the list because of the way the loop is written; at each step, it's replacing the whole text string with the link, so if you iterate through the string from the beginning, you will replace any `#` with a link to a `#` which will then get matched again and you get stuck in an infinite loop. Am I reading that right? This is just my initial glance.

I'm not sure how old the code base is, it's possible `ReverseProxy` was a workaround before `reversed` was added, or some type of bug. But I agree that we can probably ditch the custom class and rewrite the regex loop to maybe not even need reversing anymore. Let me play with some patches as I look at #511 and #513 too.

**Comment by mrkiwi-nz** [comment]
I think you're right that it goes backwards because the side effect of line 41 is to make the string longer, thereby causing any match with a higher index to change.
I also presumed that reversed was not available, or that the custom class was enabling backward compatibility with a very old python version, but i haven't investigated.
I'm happy to submit a PR with tests if you want to spend time on other tickets instead?

**Comment by gwasser** [comment]
Sure, PRs always welcome! I think we probably need some tests for this function if it doesn't already exist (I'm not sure).

**Comment by gwasser** [comment]
I'll look at other tickets for now. I'm happy to take a look if you end up busy, but I appreciate the help in the meantime! Thanks!

**Comment by mrkiwi-nz** [comment]
It has no coverage at present

**Comment by mrkiwi-nz** [comment]
Not sure what I did wrong here, but @alexbarcelo fixed this 8 months ago in commit https://github.com/django-helpdesk/django-helpdesk/commit/24d88be8d92bb108a73c7a6c710afd1ef1afb987

I guess i was looking at a pip install instead of master.

Thanks Alex!

**Comment by gwasser** [comment]
Oh ok great! Less work for us to do now then :-)

Yeah I think we really need to get 0.2.0 out, I think the difference in features between 0.1.x and 0.2 (master) is growing too much and confusing people.
