### ISSUE TITLE
Use custom templates

### ISSUE THREAD

**Issue by ElAutoestopista** [django-helpdesk/django-helpdesk#555]
Hi all,
It's possible to use custom templates without modifying the included with the packages? Like pointing to a path with a setting or similar.
If it's not possible, it would be appreciated create a setting to do this.
Thank you!

**Comment by gwasser** [comment]
Since this project is based on Django, in principle it should be possible to replace all of the built-in templates with your own custom templates. You just need to drop your templates into their own folder in your Django project directory, and tweak your settings to search your custom files before the built-in ones. You can read https://docs.djangoproject.com/en/1.11/topics/templates/ for more details.

You would need to make sure your templates include all of the same template tags and such as the originals, or they may not render correctly. But otherwise, you should be able to customize as much as you want!

**Comment by ElAutoestopista** [comment]
Thanks!! Changing the Django configuration properly. I've managed to use my custom templates, and it did the trick!
