### ISSUE TITLE
Some 'hopefully useful" criticism 

### ISSUE THREAD

**Issue by RamezIssac** [django-helpdesk/django-helpdesk#577]
Hello Team Django-HelpDesk
First of all , Thank you for publishing this work and making it available, open-source and free of charge.
I started using your code and i'm facing many -many- troubles, i don't know where to start actually.
What i aim by this comment is to help next releases designs decisions and implementation.

App Design:
* The architectural design have many assumptions built-in , like the actual use of local mail server, this becomes clear as queue mail settings does not differentiate between incoming and outgoing settings, 
And, in lib.py line 125 ,i believe, the exception is not casted into `e` so the actual use of this part of code would raise global name e not defined which points out that this part of code was never really executed before.
* It's also very hard to substitute small parts of the application without seriously hacking it. 
You can use options like dotted path for critical functions .. something like  `SEND_TEMPLATED_EMAIL_FUNCTION = 'myapp.handlers.mycustomfunction' `
So i can tweak this critical procedure if i want without overriding forms methods that calls inside the send function. Also you can use swappable models for model tweaking.

Template design:
And i mean the blocks.. It's very hard to simply edit, or integrate the html into the exiting  theme with blocks name always having `helpdesk_` as a prefix in them instead of the generic `extra_head`, `content` etc.

While of course this app is serving you and your use-case at its best, but it's not yet designed to be easily configured for other different uses. And the fact that you're the highest helpdesk/ticketing rated package on djangopackage should (i believe) direct development more towards making it easier to configure, not hack.

Thank you for your time reading this, and for publishing your work -of course- and again.

**Comment by RamezIssac** [comment]
Bug: 
You give the option to edit the email subject sent to the submitter, -where i can remove the [ticket.id]-  And i find later that the get_mail uses this id in regular expressions to detect the ticket record, and i don't believe that i read a warning against this change in the docs :)

**Comment by gwasser** [comment]
Hello, thanks for the comment. `django-helpdesk` was originally designed by its main developer for his own use, so we've been working to allow more customization over time. It was also written for a much older version of Django in Python 2, so we've been slowly adapting it to Django 1.11/2.x and Python 3 so unfortunately there are still some errors floating around. We've been expanding our unit testing to catch things but it is still not perfect. Pull requests are welcome, so please submit changes and extra tests if you'd like!

I fixed the missing exception handling you suggested, thanks! For the second bug, where can you edit the subject and remove the [ticket.id]? I didn't see it in the Email Templates admin page.

**Comment by RamezIssac** [comment]
Thank you for your reply 
It's In the settings:
HELPDESK_EMAIL_SUBJECT_TEMPLATE = "{{ ticket.ticket }} {{ ticket.title|safe }} %(subject)s" 

The `get_email.py` uses that first part of the subject when pulling mails from the box to identify the ticket.

**Comment by RamezIssac** [comment]
Allow me to elaborate more on the enhancements i would like to see and contribute to. Ordered by importance.

* Use a Class Adapter as an interface between the code and the settings. This adapter should control almost everything. Forms , redirection, sending emails, receiving emails, generating text.. everything.  And it can be assigned in settings.py via doted path.
Kindly refer [here](https://github.com/pennersr/django-allauth/blob/master/allauth/account/adapter.py) for an actual example from the `django-allauth` package.
Use Cases: 1- Developer needs a simple ticket where end user don't have access to due_date, priority, assigned_to. 2- developer wants to override the ticket absolute_url, 3- Override email template used based on context. 

* Unless i'm seriously missing something, the queue email settings are only for incoming, Outgoing email  (ie sending the submitter Ticket opened) uses the `from_email` of the queue settings and the other credentials (host, password, port, etc) from the default django settings.
This is wrong as queue point out to sales@domain.com and my "default" email is notification@domain.com. 
So, Adding outgoing mail settings to  the queue fields.

* Differentiate between the demo (which is in fact your exact use case) and the re-useable  app. Make the demo a separate app maybe within the package that gets activated only if installed. 

* Maybe use [Swappable Models](https://github.com/wq/django-swappable-models) for models tweaking.

**Comment by gwasser** [comment]
Thanks for reporting the issues with the custom email subjects. I added documentation about this problem, and a simple python check that the template includes `ticket.ticket`. Hopefully this is sufficient to alert people of the problem.

As for your other comments:

- Class Adapter is probably a good idea to go along with #372. This project started on an older version of django and so uses function based views rather than classes, so work is needed to move toward more modern classes.
- I think your suggestion about queue email settings is captured in #336. Per-queue SMTP settings is a goal for the project, not quite there yet.
- The demo is meant as an example project to show how to set up a basic helpdesk instance that uses the app, and to allow someone new to the project to play with how it looks with minimal work. If the documentation needs more work to make it distinct, let me know or send a PR with your suggestions.
- Swappable Models sounds interesting, thanks for the link. I think our goal is to have minimal dependencies so we'd have to consider the benefits, and if I understand correctly, we'd need more class-based functionality first anyway.

All of this could use some work so please let me know if you'd like to contribute to any of it. Big changes like this would go on the `develop` branch for the next major release. (`develop` may be a little bit of a mess currently as I merged a few other feature requests and haven't quite sorted out the bugs yet, but feel free to contribute to that effort too!).

**Comment by gwasser** [comment]
Since I believe your comments are now captured on related tickets, I'm going to close this one just so there are no duplicates running around, but feel free to reopen or add new tickets if you'd like, or even submit a PR!
