### ISSUE TITLE
Question: Django 2.0 support

### ISSUE THREAD

**Issue by menoz** [django-helpdesk/django-helpdesk#580]
Hi,
first of all thank you for your great work, this app is gorgeous!

But can you please tell me when you plan to add Django 2.0 support?
We'd like to include your app in a production 2.0 django application, and at least an indication of when this will be possibile would be really appreciated.

Thank you
Daniel

**Comment by gwasser** [comment]
Hello! Honestly I haven't looked at Django 2.0 yet so I'm not sure how much may need to change to support it. I'm ironing out the kinks in Django 1.11 and my understanding of Django's release process is that 2.0 will support things from 1.11 (but mark as deprecated) so in principle it should work with 2.0 very soon if not already.

So I think the short answer is: it might already, and if not, probably very soon! If you'd like to test it with 2.0 right now, let me know what if any bugs you come across. Otherwise I plan to take a look at 1.11/2.0 feature support soon with some upcoming holiday time. Thanks!

**Comment by menoz** [comment]
Yep,
I found that there are a lot of easy things to fix (mostly adding "on_delete=models.CASCADE," to model's foreignKeys and replacing "django.core.urlresolvers" with "django.urls" ), but now I'm stuck to a strange (for me, at least) error on helpdesk/decorators.py - line 17, an exception that says:

'bool' object is not callable

I'm stuck here. But no rush, I'm in no hurry :-)
Happy holidays!

**Comment by gwasser** [comment]
I haven't seen that exception so far, but it looks like at least one of our dependencies isn't Django 2.0 ready (at least `django-bootstrap-form`) so could be some interaction.

**Comment by gwasser** [comment]
Oh I completely misunderstood the logs. I think the dependencies actually might work. I fixed the easy warnings in the log in the 0.2.6 release. But when I tried to run it in Django 2.0 I got some bytes padding errors in `get_email`, so probably need a more thorough look at that.

**Comment by gwasser** [comment]
I just pushed 0.2.7 release with some more Django 2.0/Python 3 bugfixes. Let me know if you run into any problems!

**Comment by timthelion** [comment]
Just to let you know, we are testing the develop branch on Django 2.0.8 and haven't seen any bugs related to Django2. Seems good to go at least on `develop`.

**Comment by gwasser** [comment]
The `develop` branch for the next 0.3 release runs unit tests and such exclusively on Python 3 / Django 2.x now so we've got this pretty well covered! If you have some time to do so beta testing on the `develop` branch, please let us know how it goes!
