### ISSUE TITLE
How to use knowledgebase?

### ISSUE THREAD

**Issue by goetzk** [django-helpdesk/django-helpdesk#581]
Hi,
I have looked in the docs and at the demo site and I can't figure out how to add things to the KB. 

I'm not sure if there is an element missing from the UI (logged in as demo) or if there is a need for detailed documentation.

**Comment by gwasser** [comment]
I believe the demo's `demo` user is a pretty locked down one without permission to add categories to the KB. I'm not sure why that's the case, I'll have to look into that, but it might take updates to our permissions system to make that feasible.

In the meantime you should be able to see how this works on a local instance. Clone the repo and run `make rundemo` (or copy the demo folder and run it however you like) and checkout your local instance on `localhost:8080`. When you log in you should see KB settings in the System Settings menu where you can add categories and items.

The KB hasn't received as much attention as some of the other parts of `django-helpdesk` in recent releases (in particular, since our move to python 3 and modern django), so if you encounter any trouble, please file a new issue. Pull requests are always welcome!

**Comment by goetzk** [comment]
Thanks for that, I will try and find time to run up an instance myself.

If demo is unable to add KB articles in the current setup, does that mean KB articles are either public or not? I'm interested in having two groups of users (plus public) with access to different articles though might be able to fudge it somehow if helpdesk doesn't support that.

**Comment by gwasser** [comment]
Like I said, `make rundemo` runs a little demo site right out of the box to show how it works. I wouldn't recommend those settings for a real usage, but it's quick to get you started and give examples.

You might be able to make two groups, but to be honest the permissions system needs a good overhaul. If you give it a shot, let me know how it works out or if you have comments/bug reports.

**Comment by gwasser** [comment]
I'm going to close this for now to clean up the ticket view, but please reopen or create a new ticket if you encounter any problems.
