### ISSUE TITLE
demo attachment error

### ISSUE THREAD

**Issue by lbopp42** [django-helpdesk/django-helpdesk#626]
Hello,
On your demo website (http://django-helpdesk-demo.herokuapp.com) when I put an attachment in a ticket and I go on it, I got a "Page not found (404)".
I have the same problem in my own django-helpdesk. I have a question so:
How to config MEDIA_URL and MEDIA_ROOT with the default install ?

Best regards,
BOPP Lucas / System administrator at SIMCO

**Comment by gwasser** [comment]
The demo site. because of the way it is set up, isn't able to keep attachments. I'll have to update the configuration and add text to the banner that it is not possible to add attachments.

If you look at the code, there is a `demo/` folder that has an example configuration on how to set up the `MEDIA_URL` and `MEDIA_ROOT` values. It depends on exactly where you want to store the files of course. But as far as I know that local demo runs and can handle attachments (I have used it before in testing new features) so please try that and let me know if you have a problem.

**Comment by lbopp42** [comment]
Hello,
I had copy the MEDIA_URL and the MEDIA_ROOT of the demo with same directory but that don't work. I have the same 404 error page:
```
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
```

And this is a tree of my app:

```
─>tree
.
├── helpdesk_nginx.conf
├── helpdesk_uwsgi.ini
├── manage.py
├── media
│   └── helpdesk
│       └── attachements
├── static
│   ├── admin
│   └── helpdesk
└── ticket
    ├── __init__.py
    ├── __pycache__
    ├── settings.py
    ├── urls.py
    └── wsgi.py
```
If you can say what are MEDIA_URL and MEDIA_ROOT for me, I would be grateful.
Best regards,

BOPP Lucas / System administrator at SIMCO

**Comment by lbopp42** [comment]
I have found but now I have a problem with perms. The file uploaded is create with 600 perm and I need it with 660 perm.

**Comment by lbopp42** [comment]
It's ok now thanks. Have a good day.

**Comment by gwasser** [comment]
Great! Let me know if you run into any other problem. Those values are general Django settings so you'll want to read the django docs for more info.

**Comment by gwasser** [comment]
I updated the demo site to use the latest release (0.2.10) and include a message about not allowing attachments. Thanks for reporting!
