### ISSUE TITLE
Are the attachments protected?

### ISSUE THREAD

**Issue by johanovic** [django-helpdesk/django-helpdesk#647]
I see that html emails are stored in the media folder (which is nice), but I do have a question. The url is

> /media/helpdesk/attachments/email-44/119/email_html_body.html

Does that mean these attachments are all public? That would be a major problem. Anyone aware of the name of the ticket queue could start reading other people's email. 

Or am I missing something?

**Comment by gwasser** [comment]
Confirmed using the demo, I could navigate directly the to the attachment URL even though I wasn't logged in. Thanks for reporting! This is definitely a potentially big issue since the URL is largely guessable. A persistent user could simply keep trying values until found one that worked, and at least read some emails.

We've been working on cleaning up the user permissions and access code lately in the `develop` branch so I'll mark this as a bug/security issue and we'll try to think of a solution before the next release. It seems like we could add some user checks on any attachment URL to ensure you must be logged in to view.

**Comment by johanovic** [comment]
I can't find it right now (under time pressure) but whilst navigating through the code/PR's yesterday I saw that someone had added a UUID to secure the public ticket display. Something ?ticket=...?email=...?key=...  

This type of unique key for a ticket would make a lot of protection easier.

I've used an alternative solution with send_file (or its alternative on nginx) to serve protected files, which is also an option, but which does not work out of the box. 

Yet another alternative is to create an protected media folder which serves the attachments in a django view. That has the advantage of working out of the box, but the disadvantage that django actually handles the static files. For email this might not be such a huge issue given the limited size of attachments. Also for a helpdesk there won't be 1000s of simultaneous requests anyway.

**Comment by johanovic** [comment]
Found it, and... you wrote it :)

https://github.com/django-helpdesk/django-helpdesk/commit/a3bc6ed46bb1a00ce4664dfeac155e4b11b842a8#diff-1bf25f6a5d5de1ed7c39dbbd61760137R488

**Comment by gwasser** [comment]
I can't take credit, I just did the merge request :-) this was a great start by @timthelion.

We might be able to use the extra URL keys to protect it as you suggested.

**Comment by timthelion** [comment]
This might be a very easy fix. Simply change:

https://github.com/django-helpdesk/django-helpdesk/blob/develop/helpdesk/models.py#L784

To

    
    path = 'helpdesk/attachments/%s/%s' % (instance.followup.ticket.ticket_for_url, instance.followup.secret_key)

And write a test ;)

I haven't tried it though.

**Comment by gwasser** [comment]
Thanks! I haven't recently had time to test but will try to do so soon unless you'd like to and have the time to do so first.

**Comment by johanovic** [comment]
Alternatively we could simply change the actual id of the ticket. I mean, it does not have to be sequential, it can be a uuid. This would make the entire system more secure.

**Comment by timthelion** [comment]
I considered that and chose not to do it simply because it seems convenient within a team to have some short way of identifying tickets, and ticket numbering is standard practice. For example, right now, we're talking about ticket number #647. I was also asked to maintain the ability to include a search by ticket number box. Finally, and I'll admit that this may be due to my lack of Django knowledge, I didn't know how to change the ID field to a CharField and maintain backwards compatibility. Perhaps it is as simple as writing a migration, but I didn't know how to do it at the time and seemed a bit like black magic to me ;)

**Comment by gwasser** [comment]
While we've never had an "official" long term support release, I do want to keep backwards compatibility as much as possible to help current users migrate. So that's definitely a concern about going from sequential IDs to UUIDs.

Most competitor ticketing systems for example JIRA do the same thing and utilize sequential IDs, so I think it's more or less industry practice. Using more secure auth checking before returning content is probably what they do, and we should do too.

**Comment by johanovic** [comment]
Just to follow up, this is the recommended way of protecting attachments in the docs:

> Ensure that your attachments folder has directory listings turned off, to ensure users don’t download files that they are not specifically linked to from their tickets.
> If  you are using Apache, put a .htaccess file in the attachments folder with the following content:
> Options -Indexes
> You will also have to make sure that .htaccess files aren’t being ignored.
> Ideally, accessing http://MEDIA_URL/helpdesk/attachments/ will give you a 403 access denied error.

**Comment by gwasser** [comment]
Thanks! That makes sense why I saw it in the demo but it wasn't reported before. The demo doesn't have a fully configured apache to prevent this access. So in that case the issue is mitigated but we still might want to protect these URLs internally to Django with appropriate access control.

**Comment by timthelion** [comment]
shouldn't this be closed now?

**Comment by gwasser** [comment]
I ideally want to add some unit tests so keeping it open to remind myself about that :-)

**Comment by gwasser** [comment]
I'm going to go ahead and close this for now, thanks!
