### ISSUE TITLE
Feedback wanted: Would it be OK to change the behavior for deciding which side follow-ups are shown on?

### ISSUE THREAD

**Issue by timthelion** [django-helpdesk/django-helpdesk#655]
Right now, in the ticket view, followups are shown on the left or the right based on whether the follow-up originated from within the system, or whether it was sent by email. (except for the first message which is always on the right)

https://github.com/django-helpdesk/django-helpdesk/blob/master/helpdesk/templates/helpdesk/ticket.html#L86

![followups](https://user-images.githubusercontent.com/1391608/47512123-d58a7c80-d87b-11e8-9e97-dd78f9f030b7.png)

I feel like it would be more logical if the right column was always for the ticket creator, and the left column was for other users. The current behavior leads to a weird situation in which sometimes the ticket creator's messages are on the left rather than than on the right.

**Comment by gwasser** [comment]
Hmm not sure the logic making that happen. I think the idea was to do something like what you are talking about (ticket creator on the left, replies on the right). It was an experiment that I think didn't work out too well since it's really a stream of data that includes system messages too (like ticket priority changed, etc.), not just ticket creator and user messages. Not to mention it ends up wasting a lot of screen space, at least with how it works now. I have a nearly finished new Bootstrap 4 UI that will probably go back to a single stream behavior.

**Comment by timthelion** [comment]
Will the new view have any side preference? I would prefer if it did, personally, though I agree with the argument that the current display wastes space. But something like this:

!(mobile chat interface)[https://proxy.duckduckgo.com/iur/?f=1&image_host=http%3A%2F%2Fdash.coolsmartphone.com%2Fwp-content%2Fuploads%2F2013%2F07%2Fios_screen_chat.png&u=https://dash.coolsmartphone.com/wp-content/uploads/2013/07/ios_screen_chat.png]

preserves the attribute of showing direction of message flow without wasting space. I'd like to preserve the display of direction flow.

**Comment by gwasser** [comment]
I definitely prefer to do something like text message apps that still displays flow while not wasting so much space. I'll see what I can do and let you know when I merge to `develop` but you can see a sneak preview on my personal fork.

**Comment by gwasser** [comment]
The latest update to `develop` uses a new Bootstrap4 template that goes back to the single stream follow ups. I'm not sure if it would be easy to add a direction tag of some sort to it but we can explore that. I'm going to close this ticket though as the original issue is fixed.
