### ISSUE TITLE
change language and login

### ISSUE THREAD

**Issue by hd-dev** [django-helpdesk/django-helpdesk#709]
hi
very thank you for this project, its cool , and useful
i have 2 questions:
1- in directory of project , i can see many language , how can i change langue?
2- send tickets is open to public, how can do private it? for example only users in users model, or same it, how can enable login for send tickets ?

veryyyyyyyyyyyy thanks for your gooood system, i love django-helpdesk

**Comment by gwasser** [comment]
1- Since this is a django project, follow the instructions on enabling internationalization and picking a default language from the django documentation: https://docs.djangoproject.com/en/2.1/ref/settings/#std:setting-LANGUAGE_CODE

2 - the public interface can be turned off so that only logged in users can access the tickets.

**Comment by timthelion** [comment]
See https://github.com/django-helpdesk/django-helpdesk/blob/master/docs/settings.rst for documentation on configuring public access.

**Comment by gwasser** [comment]
I'm going to close this ticket but if you have other questions please file a new one!
