### ISSUE TITLE
Network Map interface with Customizable Icons that link to tickets / ticket groups

### ISSUE THREAD

**Issue by alligatorbait** [django-helpdesk/django-helpdesk#888]
**Is your feature request related to a problem? Please describe.**

The idea is to be able to create graphical dashboards of logical items like computers, network connections, and whatever else someone dreams up. With the logical items linking to a specific ticket / ticket group users can easily click on an item in the dashboard and be taken to any open ticket to continue work on any existing problems or get status on the work being done.

**Describe the solution you'd like**
1. Graphical Dashboard: (Something like a customized network map)
    https://duckduckgo.com/?q=network+map&iax=images&ia=images

    1. Logical Items Icons:
        Each logical item can be defined with an icon, admin can use their own icons.
    2. Logical item Connections:
        Connections can be created between logical items, and the connections themselves might be associated with tickets, TBD.
    3. Logical Item Tickets:
        Logical items would link to a ticket / ticket group.
    4. Logical Item Status:
        Each logical item can have a status (Green, Yellow, Red [customized by admin]) associated with ticket status.
        Green - No open tickets for the logical item.
        Yellow - Question ticket open, maybe a problem, but more information is needed.
        Red - Problem ticket open.

**Describe alternatives you've considered**
A mess of tickets submitted by users in a variety of locations that duplicate existing problems because they didn't know there was a current ticket, making more work for administrators to manage the mess of information that could have been handled by a cleaner purpose built interface.

**Additional context**
Not right now. Let the discussion begin. I'm hoping someone has some cool way to do this. I was considering building this outside of helpdesk, but think it will solve problems for more than just myself and we can collaborate on a solution that will remain integrated with helpdesk.

**Comment by timthelion** [comment]
This is actually already possible. Simply code up your diagram in HTML/CSS and stick it in the dashboard template [example](https://github.com/auto-mat/klub/blob/diakonie/apps/aklub/templates/helpdesk/dashboard.html) . Categories already exist in master (tickets can be associated with KBitems).

KBItems are already displayed in the dashboard by default:

https://github.com/django-helpdesk/django-helpdesk/blob/0e9358e61b620552d4fdfa58feaf20886f7e6bfc/helpdesk/templates/helpdesk/include/unassigned.html#L42

You just need to change the HTML so that it shows them in the graphical way you want them to be shown.

You can link to a query for a KBItem by using a url in the form:

`example.com/desk/tickets/?sortx=created&status=1&kbitem=20` where 20 is the id of the KBItem.

**Comment by alligatorbait** [comment]
Oh Wow, thanks. I will give this a shot!

**Comment by alligatorbait** [comment]
Suggestion from @timthelion did the trick. Placed as part of ticket_list.html override. Is not a simple solution, but using embedded svgs and the knowledge base recommendation you can create powerful diagram solutions.
