### ISSUE TITLE
Join two table and show combined result in Django with pre defined tables in MySQL database

### ISSUE THREAD

**Issue by divyankgarg** [django-helpdesk/django-helpdesk#953]
I have pre defined tables- functions and resources in MySQL database. I am able to connect to these individual tables separately in django but I want to join these tables based on function_id and show the combined result.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/39147665/111987388-6d800500-8acc-11eb-939e-c35ce2d97046.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/39147665/111987398-707af580-8acc-11eb-9c72-fbe02a15009e.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/39147665/111987400-71138c00-8acc-11eb-8832-853c1ba1f1d9.png)
I tried with foreign key but getting error as shown below.
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/39147665/111987401-71ac2280-8acc-11eb-9718-0d944957b0ed.png)
PLEASE PROVIDE SOLUTION FOR JOINING TABLES AND VIEWING THE COMBINED TABLE RESULT

**Comment by Benbb96** [comment]
That doesn't seem to be related to **django-helpdesk**...
You should ask your question on https://stackoverflow.com/ and prefer to post your code as formatted text instead of screenshots.

One thing I would say about your code is you should replace `function_id` by only `function` because Django will automatically map the Python field to the `[name-of-field]_id` SQL column. Then run `makemigrations` and `migrate` commands.

**Comment by gwasser** [comment]
Since this is a generic django question and not related to helpdesk, I'm going to close this ticket.
