### ISSUE TITLE
attachments are not deleted

### ISSUE THREAD

**Issue by dev72** [django-helpdesk/django-helpdesk#976]
Hello,
when I delete an issue attachments are still in media folder.
I think they should also be deleted.

**Comment by timthelion** [comment]
Seems like maybe the first answer here could be coopted: https://stackoverflow.com/questions/16041232/django-delete-filefield but the reason this was removed from django (as explained in the answer) remains. If the transaction is rolled back, you end up in an inconsistent state. Perhaps, instead, files should be cleaned up during the mail getting task... Not sure really.

**Comment by gwasser** [comment]
Exactly, files are not removed automatically/by default in order to allow
the database to remain in a consistent state should you decide to
"undelete" or roll back. I think even the tickets and such don't actually
get deleted, only marked as "deleted" in the database so they don't show up
in queries. We could create an admin tool to search the database and
filesystem for outdated data and files (say, older than 30 days?) and
permanently remove it but right now nothing like that exists.

**Comment by dev72** [comment]
there is no way to undelete or rollback after successful deletion: tickets are deleted from table.
Should simply delete attachments after the deletion transaction ended without errors.

**Comment by gwasser** [comment]
I'll have to look into this more to see exactly what the code does. maybe
we changed the default over all the work the last year. if it is not
removing attachments automatically with the ticket, we should fix that.

**Comment by uhurusurfa** [comment]
Probably best to make it a configurable option globally for now and use this project:
https://github.com/un1t/django-cleanup

The documentation can be updated to specify the settings file to including the library explicitly or  exclude it if there is an environment variable set something like:
```
    if "true"== os.getenv("DELETE_ATTACHMENTS_ON_FILE_SYSTEM", "true"):
        INSTALLED_APPS = INSTALLED_APPS + ("django_cleanup.apps.CleanupConfig",)
```
The solution becomes a documentation one.

**Comment by gwasser** [comment]
django cleanup sounds like the right solution, thanks @uhurusurfa
